name: continuous-refactor
description: Periodic refactor workflow alongside implementation.
triggers:
  - type: manual
steps:
  - prompt_id: prompt.refactor_scan
    every: 3
  - prompt_id: prompt.checkpoint_implementation
