name: refactor-cycle
description: Run continuous refactor cycle without the minor-only stop threshold.
triggers:
  - type: manual
steps:
  - prompt_id: prompt.refactor_scan
  - prompt_id: prompt.refactor_execute
  - prompt_id: prompt.refactor_verify
